FROM quay.io/fedora/fedora-silverblue:latest

# Debloat
RUN rpm-ostree override remove \
    toolbox \
    firefox firefox-langpacks \
    yelp yelp-xsl yelp-libs \
    gnome-tour \
    gnome-shell-extension-apps-menu gnome-classic-session \
    gnome-shell-extension-background-logo \
    gnome-shell-extension-launch-new-instance \
    gnome-shell-extension-places-menu \
    gnome-shell-extension-window-list

# RPM-Fusion
RUN rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && rpm-ostree install rpmfusion-free-release rpmfusion-nonfree-release

# Drivers
# RUN rpm-ostree override remove mesa-va-drivers mesa-vpdau-drivers --install=mesa-va-drivers-freeworld --install=mesa-vdpau-drivers-freeworld
# RUN rpm-ostree override remove mesa-va-drivers --install=mesa-va-drivers-freeworld --install=mesa-vdpau-drivers-freeworld
# ERROR: mesa-filesystem not found

# FFmpeg & Codecs
RUN rpm-ostree override remove libavfilter-free libavformat-free libavcodec-free libavutil-free libpostproc-free libswresample-free libswscale-free --install=ffmpeg
RUN rpm-ostree install gstreamer1-plugin-libav gstreamer1-plugins-bad-free-extras gstreamer1-plugins-ugly gstreamer1-vaapi steam-devices

# Packages
RUN rpm-ostree install \
    distrobox \
    libvirt virt-install virt-manager \
    adw-gtk3-theme yaru-theme \
    ffmpegthumbnailer \
    gnome-shell-extension-caffeine \
    gnome-shell-extension-gsconnect nautilus-gsconnect \
    gnome-shell-extension-appindicator \
    gnome-shell-extension-blur-my-shell \
    gnome-shell-extension-dash-to-dock \
    podman-compose podman-plugins \
    adobe-source-code-pro-fonts cascadiacode-nerd-fonts jetbrains-mono-fonts-all mozilla-fira-mono-fonts ubuntu-nerd-fonts ubuntumono-nerd-fonts

# Auto updates
RUN sed -i 's/#AutomaticUpdatePolicy.*/AutomaticUpdatePolicy=stage/' /etc/rpm-ostreed.conf
RUN sed -i 's/#LockLayering.*/LockLayering=true/' /etc/rpm-ostreed.conf
RUN systemctl enable rpm-ostreed-automatic.timer
