FROM containerfile-master AS base

# Drivers
# ERROR: RUN rpm-ostree override remove mesa-va-drivers --install=mesa-va-drivers-freeworld --install=mesa-vdpau-drivers-freeworld    
# RUN rpm-ostree install mesa-va-drivers-freeworld mesa-vdpau-drivers-freeworld #--allowerasing

# COPR

# Codecs
RUN rpm-ostree install gstreamer1-plugin-libav gstreamer1-plugins-bad-free-extras gstreamer1-plugins-ugly gstreamer1-vaapi steam-devices

# PROGRAMS
RUN rpm-ostree install \
    steam goverlay corectrl \
    chromium \
    file-roller \
    loupe celluloid
