FROM quay.io/fedora/fedora-kinoite:latest

# Auto updates
RUN sed -i 's/#AutomaticUpdatePolicy.*/AutomaticUpdatePolicy=stage/' /etc/rpm-ostreed.conf
RUN sed -i 's/#LockLayering.*/LockLayering=true/' /etc/rpm-ostreed.conf
RUN systemctl enable rpm-ostreed-automatic.timer

# RPM-Fusion
RUN rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# Drivers
RUN rpm-ostree override remove mesa-va-drivers --install=mesa-va-drivers-freeworld --install=mesa-vdpau-drivers-freeworld

# Debloat
RUN rpm-ostree override remove \
    kwalletmanager5 pam-kwallet \
    plasma-welcome

# COPR
# https://copr.fedorainfracloud.org/coprs/gloriouseggroll/nobara-39/

# Steam
RUN rpm-ostree install \
  steam \
  goverlay \
  corectrl

# Packages
# RUN rpm-ostree install \
    ffmpegthumbnailer \
    haruna \
    chromium \
    kate

# Distrobox
RUN rpm-ostree install distrobox

# Virt-manager
RUN rpm-ostree install libvirt virt-install virt-manager

# FFmpeg & Codecs
RUN rpm-ostree override remove libavfilter-free libavformat-free libavcodec-free libavutil-free libpostproc-free libswresample-free libswscale-free --install=ffmpeg
RUN rpm-ostree install gstreamer1-plugin-libav gstreamer1-plugins-bad-free-extras gstreamer1-plugins-ugly gstreamer1-vaapi steam-device
